#version: '3.8'

############## NETWORKS ############## 

networks:
  inception_network:
    name: inception_network
    driver: bridge

############## VOLUMES ################

volumes:
  mariadb_data:
    driver_opts:
      o: bind
      type: none
      device: /home/bsantana/data/mariadb
  
  wordpress_data:
    driver_opts:
      o: bind
      type: none
      device: /home/bsantana/data/wordpress

##############  SERVICES ############## 

services:

  # service nginx: reverse proxy
  nginx:
    depends_on:
      - wordpress
    image: nginx:42project
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always

    # mariadb: serviço de banco de dados
  mariadb:
    image: mariadb:42project
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    expose: # ainda não sei se isto está correto
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: on-failure

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:42project
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      # args:
      #   - name=value
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    restart: on-failure