#version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/html:/usr/share/nginx/html